### PR TITLE
Fixes the merge conflicts

### PR DESCRIPTION
**Pull request by mike-lvov**
Fixes merge conflicts so that GitHub can build

### CODE REVIEW

**Comment by goran-peoski-work** [comment]
What functionality is commented out? Something with setting user location?

**Comment by mike-lvov** [comment]
> What functionality is commented out? Something with setting user location?

The TalkShowStudio, which is not used in this env now(as per @sparkletown/product ). I left a few @debt comments.

**Review by jonboutelle — APPROVED** [review]
Good if it goes!

**Comment by 0xdevalias** [comment]
> What functionality is commented out? Something with setting user location?

> The TalkShowStudio, which is not used in this env now

@goran-peoski-work @mike-lvov @jonboutelle This PR basically also renders the `Audience` (aka auditorium v1) broken/unusable.. so i'm pretty certain that needs to be fixed properly.

(cc // @whoaitsaimz)

**Comment by 0xdevalias** [comment]
> This PR basically also renders the `Audience` (aka auditorium v1) broken/unusable.. so i'm pretty certain that needs to be fixed properly.

@goran-peoski-work @mike-lvov Ok, so looking with fresher eyes after sleeping I see that this is a copy of that component specifically for the TalkShowStudio, so disregard my previous comments, it seems I was wrong.

(cc // @whoaitsaimz)

**Pull request merged**
