### PR TITLE
[env/github] add default octocat avatars

### PR DESCRIPTION
**Pull request by whoaitsaimz**
(Need someone to set max number to 6 instead of 4 defaults)

[edit by @malaikaaiyar] fixes https://github.com/sparkletown/internal-sparkle-issues/issues/848

Screen Shot 2021-06-24 at 8 46 19 PM

### CODE REVIEW

**Comment by malaikaaiyar** [comment]
Done

**Comment by 0xdevalias** [comment]
@whoaitsaimz @malaikaaiyar instead of overwriting the default avatars, it would be better to just give them their own names and leave the existing files there. Then just change the file paths used in the code @malaikaaiyar chabged to reference them.

**Comment by 0xdevalias** [comment]
Compressed with ImageOptim for ~10% filesize saving:

- https://imageoptim.com/mac
- https://github.com/ImageOptim/ImageOptim

image

image

**Comment by 0xdevalias** [comment]
## Screenshots from testing locally

Edit profile screen with new defaults shown:
image

After selecting one of the Octocats (guess which one I picked! :p)
image

On the map:
image

Profile modal view:
image

**Review by 0xdevalias — APPROVED** [review]
I made some minor tweaks/optimisations, but looks good.

LGTM!

**Pull request merged**
