### PR TITLE
[staging] Updated topbar UI

### PR DESCRIPTION
**Pull request by dmitrii-zolotukhin**
closes sparkletown/internal-sparkle-issues#1185

### CODE REVIEW

**Comment by sunny-viktoryia** [comment]
@dmitrii-zolotukhin, I haven't checked the code yet. Please, fix the UI side of the PR first.

UI notes:
1. The bottom border breaks in the middle ( I've made it yellow for better visibility)
image
2. The radio button should be replaced by the one with a new design. Currently, you show both, if the venue supports radio (see the screenshot above).  The logic should be the following: if the radio for the venue is enabled, you show the new radio button which opens radio modal on click, when the radio is disabled, you don't show the radio button.
3. The mute button should work as in the burn environment - mute/unmute.
4. Please, hide "Account", "Help" menu items, as we don't have the links for them so far.
5. The search field should be expandable on hover/focus. 

not 
image

but
image

6. The topbar is not responsive, not mobile optimized. Please, find the examples in Figma.
image

7. venue name should not be all capital (as per our latest discussion with @sofisparkle), please, revert it back.
image

**Comment by dmitrii-zolotukhin** [comment]
> @dmitrii-zolotukhin, I haven't checked the code yet. Please, fix the UI side of the PR first.
> 
> UI notes:
> 
> 1. The bottom border breaks in the middle ( I've made it yellow for better visibility)
>    image
> 2. The radio button should be replaced by the one with a new design. Currently, you show both, if the venue supports radio (see the screenshot above).  The logic should be the following: if the radio for the venue is enabled, you show the new radio button which opens radio modal on click, when the radio is disabled, you don't show the radio button.
> 3. The mute button should work as in the burn environment - mute/unmute.
> 4. Please, hide "Account", "Help" menu items, as we don't have the links for them so far.
> 5. The search field should be expandable on hover/focus.
> 
> not image
> 
> but image
> 
> 1. The topbar is not responsive, not mobile optimized. Please, find the examples in Figma.
>    image
> 2. venue name should not be all capital (as per our latest discussion with @sofisparkle), please, revert it back.
>    image

1) I have a solid bottom border
2) fixed in e073da95a8f123fe1876278adda82a5ab06a889c
3) fixed in e073da95a8f123fe1876278adda82a5ab06a889c
4) fixed in e073da95a8f123fe1876278adda82a5ab06a889c
5) fixed in e073da95a8f123fe1876278adda82a5ab06a889c
6) WIP
7) fixed in e073da95a8f123fe1876278adda82a5ab06a889c

**Comment by ermiaSparkle** [comment]
If I post here it will stop notify it is stale?

**Comment by goran-peoski-work** [comment]
> 
> 
> If I post here it will stop notify it is stale?

@ermiaSparkle how about re-assign it or close it? not worth adding a comment each 10 days just to keep it as is, the list under "This branch has conflicts that must be resolved" will just keep expanding

**Pull request closed without merging**
