### PR TITLE
Add workflow to deploy per-PR 'preview' staging environments

### PR DESCRIPTION
**Pull request by 0xdevalias**
(fixes https://github.com/sparkletown/internal-sparkle-issues/issues/108)

This PR adds a workflow for deploying 'preview' staging environments from PRs so that features can be played with by non-tech users before they get merged into `staging`.

This should help us to not block `staging` with code that isn't deployable to `master`, since we will be able to test/refine in the original PR until it is 'good to go'.

- https://firebase.google.com/docs/hosting/test-preview-deploy#preview-channels
- https://firebase.google.com/docs/hosting/manage-hosting-resources
- https://firebase.google.com/docs/hosting/github-integration
  - https://github.com/marketplace/actions/deploy-to-firebase-hosting
  
## TODO

- [x] 🐛  `Error: Hosting site or target *** not detected in firebase.json` ([ref](https://github.com/sparkletown/sparkle/runs/1679853866?check_suite_focus=true))
- [x] Because the 'environment' name shows up in places, it seems a bit misleading for it to be called `staging`. I think it would be better to rename it to something like `preview` or `pr-preview` or something like that.

### CODE REVIEW

**Comment by 0xdevalias** [comment]
For the 'Deploy to Firebase Hosting Preview on PR' action to run, we need to manually approve it from the 'Checks' tab:

- https://github.com/sparkletown/sparkle/pull/1070/checks

image

This is controlled by the 'required reviewers' in the sparkletown/sparkle `staging` 'environment' settings

- https://github.com/sparkletown/sparkle/settings/environments 🔒 
- https://docs.github.com/en/free-pro-team@latest/actions/reference/environments#required-reviewers
- https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/reviewing-deployments

**Comment by mike-lvov** [comment]
Looks really good!

**Comment by 0xdevalias** [comment]
Latest preview build/deploy seems to be working! (see https://github.com/sparkletown/sparkle/pull/1070#issuecomment-758364659 for the preview URL)
image

**Review by mike-lvov — APPROVED** [review]
Good feature!

**Pull request merged**
