### PR TITLE
[env/github] remove auth-getCustomAuthConfig

### PR DESCRIPTION
**Pull request by ermiaSparkle**
remove auth-getCustomAuthConfig as https://github.com/sparkletown/internal-sparkle-issues/issues/839#issuecomment-873360254 in this comment suggested we don't need it for Github

partially fixes https://github.com/sparkletown/internal-sparkle-issues/issues/839

### CODE REVIEW

**Comment by mike-lvov** [comment]
Not sure if it's the best way to approach it. I don't think the code itself results in loading problems. May be should just comment out the Usage in `Login`? @0xdevalias wdyt?

**Comment by ermiaSparkle** [comment]
@0xdevalias

**Comment by 0xdevalias** [comment]
> I don't think the code itself results in loading problems. May be should just comment out the Usage in `Login`?

@ermiaSparkle @mike-lvov Probably just comment it out + add `@debt` comments explaining why it was commented out like we have done for some of the other things being removed/hacked out of `env/github`

**Comment by jonboutelle** [comment]
Can we drop this now that github is past? Verify with @ermiaSparkle at Monday sync-up

**Comment by 0xdevalias** [comment]
> Can we drop this now that github is past? Verify with @ermiaSparkle at Monday sync-up

@jonboutelle I think we can probably close this. It was proposed as an environment specific hack, probably wasn’t going to have a huge amount of impact on first load speed, and definitely not something we want to remove from the main codebase.

**Review by 0xdevalias — CHANGES_REQUESTED** [review]
I don't think this is a change we care about making anymore, so this PR can probably be closed.

**Pull request closed without merging**
