### PR TITLE
add clickable avatars to RoomModal

### PR DESCRIPTION
**Pull request by mike-lvov**
add clickable avatars to RoomModal.

### CODE REVIEW

**Review by goran-peoski-work — COMMENTED** [review]
why remove `isAudioEffectDisabled` prop?

**Comment by mike-lvov** [comment]
> why remove isAudioEffectDisabled prop?
It was unused. The UserList is basically the images, no logic inside

**Review by 0xdevalias — APPROVED** [review]
[CRO] Skimmed the code, makes sense to me. If tested and works, then :shipit:

**Review by alexey-petrov — APPROVED** [review]
LGTM

**Pull request merged**
