### PR TITLE
hide shoutouts from Auditorium v1

### PR DESCRIPTION
**Pull request by whoaitsaimz**
Related to shoutbox, please ignore as we now have admin toggle

### CODE REVIEW

**Review by whoaitsaimz — COMMENTED** [review]
Whoops, I meant to push a diff thing. This is for shout box

**Comment by 0xdevalias** [comment]
@whoaitsaimz So can this PR be closed then?

**Comment by whoaitsaimz** [comment]
>@whoaitsaimz So can this PR be closed as invalid then?

100%. I asked Jon to do it, wasn't sure "how"

**Comment by 0xdevalias** [comment]
If you have access to do so, there will be a big red close button.

**Comment by whoaitsaimz** [comment]
Aha! Part of the comment field. Was looking up by the issue name etc. Thanks!

**Comment by 0xdevalias** [comment]
No worries :)

**Pull request closed without merging**
