### PR TITLE
Deploy staging -> master

### PR DESCRIPTION
**Pull request by 0xdevalias**
Deploys:

- Fix iframes (#811)
- Jazz bar layout fixes (#813)
- ⚡ Artpiece participant videos converted to grid layout (#817)

### CODE REVIEW

**Comment by 0xdevalias** [comment]
`do-not-merge` is set as i'm not sure if these are ready to be merged or not, mostly wanted to use this branch to test 'Merge Freeze'

**Comment by thecadams** [comment]
Gotcha, no worries. Wont deploy just yet.

**Comment by 0xdevalias** [comment]
If things are tested and working here though, feel free to remove the label and merge this. Mostly just want to be aware of not pushing out untested/QA'd code that might impact the big event this weekend.

**Review by denisdimitrov — APPROVED** [review]
LGTM!

**Pull request merged**
