### PR TITLE
shrink video when audience aspect ratio is 16:9

### PR DESCRIPTION
**Pull request by denisdimitrov**
Not sure if this is the fix we want. Instead of enlarging the video and make it hide the top seats, now it shrinks from the sides (width only) and doesn't collide with the seats.

### CODE REVIEW

**Comment by denisdimitrov** [comment]
[Lots of people having issues logging in](https://trello.com/c/jQD4RiUw/536-lots-of-people-having-issues-logging-in)

**Comment by 0xdevalias** [comment]
@denisdimitrov is this a change only required in this 1 file? I believe the original PR touched a couple of different scss files to implement 16:9 Do we need to make fixes in all of those locations?

**Comment by denisdimitrov** [comment]
@0xdevalias The task is specifically for `audience` template, the other change is in Artpiece but it's using padding and seems to be working fine.

**Comment by 0xdevalias** [comment]
@denisdimitrov great. Thanks for the explanation. I'm guessing you've played around with this change, resized things, etc and it seems to be working ok?

**Comment by denisdimitrov** [comment]
[Auditorium video is bleeding into the seats (EVENT: 12/10@4:45am AEDT)](https://trello.com/c/e0j4kMxb/532-auditorium-video-is-bleeding-into-the-seats-event-12-10445am-aedt)

**Comment by denisdimitrov** [comment]
@0xdevalias I found a 16:9 video in one of the production urls and this was looking good and responsive. It also works good when the "16:9" is missing from the firebase, the video is just slightly smaller.

**Review by 0xdevalias — APPROVED** [review]
As per @denisdimitrov's comments in https://github.com/sparkletown/sparkle/pull/938#issuecomment-741775896 it sounds like this is good to go!

No concerns with the code changes here. LGTM!

**Review by thecadams — COMMENTED** [review]
👍

**Pull request merged**
