### PR TITLE
Fixes flatmap error in Edge browser

### PR DESCRIPTION
**Pull request by mike-lvov**
Adds polyfill for flatMap

### CODE REVIEW

**Comment by mike-lvov** [comment]
[React error - object or property does not support flatMap](https://trello.com/c/2GUZofrP/545-react-error-object-or-property-does-not-support-flatmap)

**Review by thecadams — APPROVED** [review]
Fantastic addition, thanks for this!

**Comment by 0xdevalias** [comment]
@mike-lvov I would have to look to be certain, but we shouldn't have any need to be adding manual polyfills like this. We should be getting them through our babel/browserslist/etc settings and transpilation. I'm guessing this PR was raised due to a specific error showing up in Edge? Do you have any more context/details/etc you're able to share here about it?

**Comment by mike-lvov** [comment]
@0xdevalias yes, there are also screenshots about this bug in the Trello ticket.

**Pull request merged**
