### PR TITLE
Allows message deletion for an admin

### PR DESCRIPTION
**Pull request by mike-lvov**
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/420

### CODE REVIEW

**Review by denisdimitrov — APPROVED** [review]
LGTM!

**Review by 0xdevalias — COMMENTED** [review]
We also have `useIsAdminUser` and related hooks in `src/hooks/roles.ts` that would have resolved this is a potentially cleaner/simpler way.

**Review by 0xdevalias — COMMENTED** [review]
@mike-lvov Actually.. further to my last review.. the logic here is actually wrong.. and introduces a security issue.

To be allowed to delete a message, I need to have both the admin role AND be an owner of the current venue, or one of the related parent venues.

The logic as implemented here means that anyone who can create any venue within this environment can delete anyone's messages, even on venues they have no access to.

**Comment by mike-lvov** [comment]
>  introduces a security issue.
> 
> To be allowed to delete a message, I need to have both the admin role AND be an owner of the current venue, or one of the related parent venues.
> 
> The logic as implemented here means that anyone who can create any venue within this environment can delete anyone's messages, even on venues they have no access to.

It doesn't introduce it. It just keeps it :). The previous implementation :

` const allowDelete =
    ((userRoles && userRoles.includes("admin")) ||
      (user && venue?.owners?.includes(user.uid))) ??
    false;`

**Pull request merged**
