### PR TITLE
remove photobooth from staging

### PR DESCRIPTION
**Pull request by alexey-petrov**
Fix as per https://github.com/sparkletown/sparkle/pull/2336#issuecomment-927959330

### CODE REVIEW

**Comment by mike-lvov** [comment]
> Let's not merge this PR until [sparkletown/internal-sparkle-issues#1142 (comment)](https://github.com/sparkletown/internal-sparkle-issues/issues/1142#issuecomment-938232924) is not answered.

Looks like we are safe to remove it

**Comment by mike-lvov** [comment]
@alexey-petrov please fix the conflicts & good to go

**Review by mike-lvov — APPROVED** [review]

**Review by goran-peoski-work — CHANGES_REQUESTED** [review]
Please do not delete it but put it under `TesterRestricted` similar as per the discussion there https://github.com/sparkletown/internal-sparkle-issues/issues/1142#issuecomment-964837961 but more towards the idea from @ermiaSparkle from the daily

**Comment by alexey-petrov** [comment]
Closed in favor of https://github.com/sparkletown/sparkle/pull/2639

**Pull request closed without merging**
