### PR TITLE
add howto on running emulators in README.md

### PR DESCRIPTION
**Pull request by goran-peoski-work**
New section in README.md for running the Firebase emulators suite

### CODE REVIEW

**Comment by 0xdevalias** [comment]
Had a quick skim, will give a more in depth review when I have capacity. Looks like a good start! I think instead of documenting the code/version changes that might be required here, we might be better to actually make them (probably in a separate PR). I have an existing draft PR for upgrading our firebase libs.

**Review by yurii-lubynets — APPROVED** [review]

**Comment by goran-peoski-work** [comment]
> we might be better to actually make them (probably in a separate PR). I have an existing draft PR for upgrading our firebase libs.

@0xdevalias 

I've already anticipated this, only, didn't think of noting it here as well, in a rush I just put a comment on the PR:
https://github.com/sparkletown/internal-sparkle-issues/issues/781#issuecomment-855750046

Basically, I pushed 2 branches, one for the docs, other for the code (minimal changes) that I used to run the stuff.
This only because I know more works needs to be done when you upgrade major version of your database adapter.

**Comment by goran-peoski-work** [comment]
Oh, branch is https://github.com/sparkletown/sparkle/tree/feature/emulators-code

**Comment by 0xdevalias** [comment]
@yurii-lubynets @goran-peoski-work As per my comments in https://github.com/sparkletown/sparkle/pull/1510#issuecomment-855763213, this PR wasn't really in a state that it should have been merged as-is. The README presents our 'front marketing' and 'first line of support' for the open source project, and how to use it. As my comments suggested, there were further changes that we needed to land + adjustments needed to be made to the text here before it was ready to be merged.

(cc // @jonboutelle FYI)

**Pull request merged**
