### PR TITLE
refactor openUrl/openRoomUrl/enterVenue to allow custom openers + use React Router for navigation in PosterPreview / NavBar's back button

### PR DESCRIPTION
**Pull request by 0xdevalias**
The changes in this PR basically pave the way to us being able to use React Router for relative link navigation, rather than having to entirely load the application every time someone changes spaces (or as @yarikoptic describes it: the "blue screen of sparkle")

- https://reactrouter.com/web/api/history
  - > `push(path, [state])` - (`function`) Pushes a new entry onto the history stack

It adds this support in `openUrl`, `openRoomUrl`, and `enterVenue` within `utils/url`.

It uses this in only 2 places currently (we can add more in future followup PRs):

- the `backToParentVenue` button in the `NavBar` component
- within the `PosterPreview` component when accessing a `PosterPage`

I want to keep the scope of this PR fairly small for now, as while it does increase the perceived performance of the app quite a bit when navigating between spaces; there are cases where we actually benefit from the "forced to fully reload the page" navigation, as it can force aspects of our code with potential memory leaks/etc to get reset/cleaned up. I'm not certain if/where/how much of an impact that will be, so I want to avoid updating this across the entire app until we have a better idea around that.

---

partially fixes https://github.com/sparkletown/sparkle/issues/1461

Will likely be useful for https://github.com/sparkletown/internal-sparkle-issues/issues/752#issuecomment-850333759

### CODE REVIEW

**Review by yurii-lubynets — APPROVED** [review]
LGTM

**Comment by yarikoptic** [comment]
Please pardon me in advance... but this is **f.cking awesome** !!!  Thank you @0xdevalias !!! 

Many steps through the venue become really nice and smooth: e.g. entering a poster from posterhall, or going back to posterhall, or going back to home is nearly instantaneous!   Some are just better, e.g. entering a venue upon "Enter" button click still shows the "blue screen of sparkle" but for shorter duration it feels.

**Comment by yarikoptic** [comment]
one interesting observation: if I go to http://localhost:3000/in/posterhall and then click on "Back home" UI element -- going back home fast.  If I use browser's "back" button -- "blue screen of sparkle" (will in the future abbreviate it as BSoS ;) ).  I do not observe that going back from a poster to posterhall -- in both cases fast.

**Review by yarikoptic — APPROVED** [review]

**Comment by yarikoptic** [comment]
> Visit the preview URL for this PR (updated for commit [aa685cd](https://github.com/sparkletown/sparkle/commit/aa685cd05d630164985c5b56a3f54cf4f7af41fe)):
> 
> https://co-reality-staging--preview-pr-1468-y7ge51oq.web.app
> 
> (expires Fri, 11 Jun 2021 09:55:19 GMT)
> 
>  via [Firebase Hosting GitHub Action](https://github.com/marketplace/actions/deploy-to-firebase-hosting)

FWIW for me it just then forwards to https://sparklespaces.com/

**Comment by 0xdevalias** [comment]
> > Visit the preview URL for this PR (updated for commit [aa685cd](https://github.com/sparkletown/sparkle/commit/aa685cd05d630164985c5b56a3f54cf4f7af41fe)):
> > https://co-reality-staging--preview-pr-1468-y7ge51oq.web.app
> > (expires Fri, 11 Jun 2021 09:55:19 GMT)
> > via [Firebase Hosting GitHub Action](https://github.com/marketplace/actions/deploy-to-firebase-hosting)
> 
> FWIW for me it just then forwards to https://sparklespaces.com/

Yeah, the root always redirects. If you add /in/devaliashacksville to the end that should take you to one of our staging environments. But that may not have much PosterHall stuff. What you have running locally is as good as using the preview link for devs generally. We more use it to share features with the non tech team, or to quickly check something.

**Comment by 0xdevalias** [comment]
> one interesting observation: if I go to http://localhost:3000/in/posterhall and then click on "Back home" UI element -- going back home fast. If I use browser's "back" button -- "blue screen of sparkle" (will in the future abbreviate it as BSoS ;) ). I do not observe that going back from a poster to posterhall -- in both cases fast.
> 
> edit: I am not implying needing to have it fixed in this PR !!! I will approve FWIW as well, it is already a priceless improvement over current state of things and if buggy -- better be detected and fixed, and for that needs use and thus merge

If you navigated directly to the page then click back, that’s a different scenario than clicking the ‘back to parent venue’ button (which is technically ‘going forward’ to a new url that happens to be the parent venue)

**Pull request merged**
