### PR TITLE
[env/burn-staging] fix loading state to schedule

### PR DESCRIPTION
**Pull request by malaikaaiyar**
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/1152

### CODE REVIEW

**Review by goran-peoski-work — APPROVED** [review]
LGTM

**Comment by daniel-brown-sparkle** [comment]
This is due to https://github.com/sparkletown/sparkle/commit/c6b6346682d4f81d4e9e95591c7b6791ee03da1c#r55837037

I propose fixing the problem at its core, so all affected components are fixed.

e.g. 

```diff
--- src/components/molecules/Loading/Loading.tsx	(revision 60b1cf3ae8997ef1e1db4991d58a20ed82bb19cc)
+++ src/components/molecules/Loading/Loading.tsx	(date 1630653160253)
@@ -15,7 +15,7 @@
 export const Loading: React.FC<LoadingProps> = ({
   containerClassName,
   label,
-  displayWhile,
+  displayWhile = true,
 }) => {
   const containerClasses = classNames("Loading", containerClassName);
   return displayWhile ? (

```

**Comment by goran-peoski-work** [comment]
PRs for reference:

- https://github.com/sparkletown/sparkle/pull/2239
- https://github.com/sparkletown/sparkle/pull/2242

**Comment by malaikaaiyar** [comment]
> I propose fixing the problem at its core, so all affected components are fixed.

Sure! I can add this

**Comment by daniel-brown-sparkle** [comment]
> > I propose fixing the problem at its core, so all affected components are fixed.
> 
> Sure! I can add this

@malaikaaiyar I think Goran fixed this already with https://github.com/sparkletown/sparkle/pull/2239 which makes this PR redundant as far as I  can tell

**Comment by malaikaaiyar** [comment]
I'll close this then

**Pull request closed without merging**
