### PR TITLE
Revert "fix Auditorium video container to be properly centred + some related cleanup"

### PR DESCRIPTION
**Pull request by mike-lvov**
Reverts sparkletown/sparkle#1231

### CODE REVIEW

**Review by denisdimitrov — APPROVED** [review]
LGTM!

**Comment by mike-lvov** [comment]
Will get back to this, when we fix all the issues. I need to unblock the staging

**Comment by 0xdevalias** [comment]
@mike-lvov I wonder if this could have just been deployed as well? I’m pretty sure that it’s no more broken than the existing Auditorium, even though it does still have a slight bug. In any case, need to make sure this gets in-reverted and not lost.

**Comment by mike-lvov** [comment]
@0xdevalias inreverted here https://github.com/sparkletown/sparkle/pull/1237

**Comment by 0xdevalias** [comment]
@mike-lvov Yeah, that's fair enough.

**Pull request merged**
