### PR TITLE
WIP: [IMPROVEMENT] Removes outdated and no longer used parts of the codebase

### PR DESCRIPTION
**Pull request by thecadams**
Targeted for removal:
- Old templates
- Old party configs from when the config was uploaded with a script
- Playa
- Dust storm (it's part of the playa)
- Placement
- Playa address
- others still to come

## TODO

- [ ] Remove `FriendShipPage` and related (see https://github.com/sparkletown/sparkle/pull/833#issuecomment-767948624)

### CODE REVIEW

**Comment by 0xdevalias** [comment]
> `src/components/organisms/Chatbox/Chatbox.tsx` usages:
> 
> - `src/pages/FriendShipPage/FriendShipPage.tsx`
>   - This looks like it is probably a legacy page, so should probably get removed in https://github.com/sparkletown/sparkle/pull/833
>   - https://github.com/sparkletown/sparkle/search?q=friendship
>
> _Originally posted by @0xdevalias in https://github.com/sparkletown/sparkle/pull/1047#discussion_r564959987_

**Comment by 0xdevalias** [comment]
Given how far the codebase has diverged since this PR was first opened, I think it might be quicker for me to start a new branch off of `staging` + delete these files again, rather than try to fix all of the merge conflicts. I will keep this PR here as a reference.

**Comment by mobilevinay** [comment]
**standup notes**
close to landing... likely move to S2.

**Comment by thecadams** [comment]
Guessing this is stale, just doing a cleanup pass on my open PRs across all projects. Going to close but feel free to reopen if needed.

**Comment by 0xdevalias** [comment]
@thecadams All good :) Stale, and I have an equally stale local branch to do similar as well, but one day we’ll properly get these tech debt bits removed! 😛

**Pull request closed without merging**
