### PR TITLE
[env/github] Fixed removing parentId

### PR DESCRIPTION
**Pull request by dmitrii-zolotukhin**
- [x] Fixed: You cannot remove parentId from admin v1 when editing venue

### CODE REVIEW

**Comment by denisdimitrov** [comment]
@dmitrii-zolotukhin We should add this to `staging` as well.

**Comment by denisdimitrov** [comment]
There is still missing code in this PR. Removing the `parentId` is not enough because the sovereign venue would still stay the same.

**Comment by dmitrii-zolotukhin** [comment]
> @dmitrii-zolotukhin We should add this to `staging` as well.

@denisdimitrov done in https://github.com/sparkletown/sparkle/pull/1851

**Comment by dmitrii-zolotukhin** [comment]
When I was working on that, I also faced with some problems, which I described below:
1. sovereignVenue doesn't reset when you delete it from input in the venue editing form - fixed
2. After resetting in redux was incorrect sovereignVenue - fixed
3. Checking on existing of sovereignVenue in DB - fixed
4. Reset of variable formError when entering new value in parentId input after appearing of error from the point 3 - fixed
5. Situation when a user enters value in parentId input equal to id of venue itself (in other words - venue eId) - fixed

**Comment by mike-lvov** [comment]
is the duplicate of https://github.com/sparkletown/sparkle/pull/1851

**Pull request closed without merging**
