### PR TITLE
remove unused jquery dependency + bootstrap import

### PR DESCRIPTION
**Pull request by 0xdevalias**
Note that even though we get the following `peerDependency` warning, it's not relevant to us, as we are only using `bootstrap` for it's SCSS, and `react-bootstrap` (which we use for the rest of the JS-related functionality) doesn't require jQuery

```
npm WARN bootstrap@4.5.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
```

**Note:** I haven't clicked through to test this fully yet, so we should do that before merging, but I expect it should be fine.

---

Background research in https://github.com/sparkletown/internal-sparkle-issues/issues/839#issuecomment-873823600

partially fixes https://github.com/sparkletown/internal-sparkle-issues/issues/839

---

**Edit:**

I'm not 100% sure.. but I seem to be getting an error when trying to build after this PR. Not sure if my local branch is just broken (been switching back and forth a lot), or if there might be something deeper that is pulling this in when trying to build for production (I'm pretty sure it worked when I tried running it with `npm start`)

```
> react-scripts build --stats

Creating an optimized production build...
Failed to compile.

./node_modules/bootstrap/dist/js/bootstrap.js
Cannot find module: 'jquery'. Make sure this package is installed.
```

---

**Edit 2:**

Looks like there's a probably unneeded `import "bootstrap";` in `src/index.tsx`, so that's probably the source of this error (and of the entire of `bootstrap` being added to our bundle, probably unnecessarily)

I've removed this now and it looks like it should work fine.

### CODE REVIEW

**Comment by 0xdevalias** [comment]
Using the following npm scripts:

```
  "build:bundle-stats": "react-scripts build --stats",
  "analyze:bundle-stats": "npx webpack-bundle-analyzer build/bundle-stats.json -m static -r build/bundle-stats.html",
```

## Bundle size before

```
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  808.4 KB   build/static/js/2.acb244af.chunk.js
  133.61 KB  build/static/css/main.e96df676.chunk.css
  130.28 KB  build/static/js/main.60ab7fb5.chunk.js
  9.49 KB    build/static/js/3.aca06453.chunk.js
  1.86 KB    build/static/css/2.ca756f56.chunk.css
  1.17 KB    build/static/js/runtime-main.b20c0baa.js
```

image

image

## Bundle size after

```
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  757.29 KB (-51.12 KB)  build/static/js/2.d3566ff2.chunk.js
  133.61 KB (+1 B)       build/static/css/main.5125acdb.chunk.css
  130.27 KB (-7 B)       build/static/js/main.7181a4f3.chunk.js
  9.48 KB (-2 B)         build/static/js/3.a560293f.chunk.js
  1.86 KB                build/static/css/2.ca756f56.chunk.css
  1.17 KB (+2 B)         build/static/js/runtime-main.3a521cfb.js
```

image

image

**Comment by denisdimitrov** [comment]
@0xdevalias 
> 
>Edit 2:
>
>Looks like there's a probably unneeded import "bootstrap"; in src/index.tsx, so that's probably the source of this error (and of the entire of bootstrap being added to our bundle, probably unnecessarily)

I'd like to verify that removing the `bootstrap` fixes the issue, I clicked through a couple of worlds and looks like everything is looking and working fine.

According to `react-bootstrap`'s getting started guide, there is a syntax to import boostrap's stylesheet [here](https://react-bootstrap.github.io/getting-started/introduction/#sass) and it doesn't break the code, but I didn't notice anything different either. One way is to remove the import or replace it with the proper syntax as a precaution.

**Comment by 0xdevalias** [comment]
> One way is to remove the import or replace it with the proper syntax as a precaution.

@denisdimitrov See my latter edit:

> I've removed this now and it looks like it should work fine.

The above stats in https://github.com/sparkletown/sparkle/pull/1720#issuecomment-873882318 is after this.

But apparently I may not have pushed that commit.. too many branch hops..

**Review by denisdimitrov — APPROVED** [review]
LGTM!

**Pull request merged**
