### PR TITLE
Remove photobooth button from admin

### PR DESCRIPTION
**Pull request by goran-peoski-work**
Turns
sparkle-photobooth-02

into

sparkle-photobooth-03

### CODE REVIEW

**Comment by whoaitsaimz** [comment]
This was a BM only thing. It just needs to be removed from staging all together. Thanks.

**Comment by ermiaSparkle** [comment]
@whoaitsaimz 
Sofi decided to have this one available in staging too.

**Review by ermiaSparkle — APPROVED** [review]
LGTM!

**Comment by goran-peoski-work** [comment]
Here is a follow up PR 
- https://github.com/sparkletown/sparkle/pull/2360

@whoaitsaimz depending on what @sofisparkle, you and @ermiaSparkle decide, it will be easy for @ermiaSparkle to review + approve + merge it or close it in favor of some other solution.

**Pull request merged**
