### PR TITLE
remove Zendesk dependency

### PR DESCRIPTION
**Pull request by ermiaSparkle**
Remove Zendesk

partially fixes https://github.com/sparkletown/internal-sparkle-issues/issues/839

**Before**
beforeMixpanel
**After**
Screenshot from 2021-07-06 10-12-36

### CODE REVIEW

**Comment by 0xdevalias** [comment]
@ermiaSparkle What about the `showZendesk` param on `Venue`?

**Review by 0xdevalias — CHANGES_REQUESTED** [review]
@ermiaSparkle What about the `showZendesk` param on `Venue` + all other related locations?

- https://github.com/sparkletown/sparkle/search?q=zendesk

**Comment by ermiaSparkle** [comment]
> @ermiaSparkle What about the `showZendesk` param on `Venue` + all other related locations?
> 
> * https://github.com/sparkletown/sparkle/search?q=zendesk

finxed in https://doesitsparkle.slack.com/archives/C01ER4M61TL/p1625627541104900?thread_ts=1625569313.087900&cid=C01ER4M61TL

**Comment by 0xdevalias** [comment]
@ermiaSparkle looks like this PR has merge conflicts with `src/pages/VenuePage/VenuePage.tsx` now. Can you please fix these up.

**Review by mike-lvov — APPROVED** [review]
LGTM

**Pull request merged**
