### PR TITLE
BM: make description/subtitle not required

### PR DESCRIPTION
**Pull request by dmitrymarchuk**
Closes https://github.com/sparkletown/internal-sparkle-issues/issues/1068

### CODE REVIEW

**Comment by goran-peoski-work** [comment]
LGTM

**Review by sunny-viktoryia — COMMENTED** [review]
when you edit the venue and remove the description (as it's not a required field anymore), the description doesn't get removed and stays as is. can you fix that, please?

**Comment by dmitrymarchuk** [comment]
Fixed in https://github.com/sparkletown/sparkle/pull/2009/commits/cf1ace28faeffa53c02b39ea6592e406666db3f2

**Comment by whoaitsaimz** [comment]
Please apply to whole product and not just env/burn

**Pull request merged**
