### PR TITLE
Admin v2 - Fix room creation with venue and room url

### PR DESCRIPTION
**Pull request by denisdimitrov**
Creating a room was not working properly because of `showGrid` instead of `data.showGrid`
Also `editValues` always exist and the venue was always being created. Now the condition has been fixed and creating a room without venue is working.

Fixes https://github.com/sparkletown/internal-sparkle-issues/issues/315

### CODE REVIEW

**Review by 0xdevalias — APPROVED** [review]
LGTM! :shipit:

**Comment by denisdimitrov** [comment]
@0xdevalias The CI seems to be stuck at `ci/circleci: lint-and-test Expected — Waiting for status to be reported` any idea how to fix this? I can't merge it because of this check.

**Comment by 0xdevalias** [comment]
> The CI seems to be stuck at `ci/circleci: lint-and-test Expected — Waiting for status to be reported` any idea how to fix this? I can't merge it because of this check.

Unsure specifically why, but one 'workaround' solution would just be to commit/push another commit to the branch, which should trigger it again?

You can check on CircleCI to see if it was ever run there, that would narrow down whether it was an issue on that side, or just an issue on GitHub receiving the 'check result': https://app.circleci.com/pipelines/github/sparkletown/sparkle

**Comment by 0xdevalias** [comment]
@denisdimitrov Merged this for you, as I was trying to create venues in `staging` and hitting this bug.

**Pull request merged**
