### PR TITLE
move profile links to the bottom of the profile; move okta data to the top

### PR DESCRIPTION
**Pull request by mike-lvov**
As per the call with @whilesocold @sofisparkle , we need to change the order of profile items

### CODE REVIEW

**Comment by sofisparkle** [comment]
image

**Comment by mike-lvov** [comment]
Result:
image

**Comment by mike-lvov** [comment]
@0xdevalias @sunny-viktoryia worth your back-checking. It's a trivial change though

**Review by 0xdevalias — COMMENTED** [review]
Retroactive review, looks fine to me 👌🏻 ✅

**Pull request merged**
