### PR TITLE
AV1 add default video for embeddables

### PR DESCRIPTION
**Pull request by malaikaaiyar**
fixes https://github.com/sparkletown/internal-sparkle-issues/issues/1078

### CODE REVIEW

**Review by sunny-viktoryia — COMMENTED** [review]
should it go to staging? I guess it's burning-man env customization, isn't it?
if so, please, change the base branch to `env/burn-staging`.

besides that, looks good.

**Comment by goran-peoski-work** [comment]
> should it go to staging? I guess it's burning-man env customization, isn't it?
> if so, please, change the base branch to `env/burn-staging`.
> 
> besides that, looks good.

This is an Admin NG thing supposed to help people who do admin tasks to just start something up and later return to fill in all the required missing pieces. It should be for all environments.

The difference with BM being that Admin NG will not be used, so Admin OG gets the same principle. Should still go into `staging` IMHO since it doesn't rely on the assumption OG version will stop being used right after BM.

**Comment by whoaitsaimz** [comment]
Please make default the Intro to Sparkle video: https://vimeo.com/512606583

This is for staging

Follow up to come for burn-staging

**Comment by malaikaaiyar** [comment]
new pr is here: https://github.com/sparkletown/sparkle/pull/2193

**Comment by whoaitsaimz** [comment]
Fab! Thanks Malaika

**Review by goran-peoski-work — APPROVED** [review]
LGTM

**Comment by sofisparkle** [comment]
Hey @malaikaaiyar can we adjust this so the default is set in the backend if the box is left blank? And remains blank for the user unless they put something in there? 
Text: "Set your URL. This can be a livestream URL, embeddable video URL or anything else which is iframe compatible (click here to learn more [open in new tab symbol] [https://docs.google.com/presentation/d/e/2PACX-1vTeoZQSP2b4q4dMceEnm_fU1QaS4u5F_n1_EnZjjn-b7N91imfRbJaDX9w1aR0QS6G3NgnZcMTaMiq-/embed?start=false&loop=false&delayms=3000]). Leave it blank and you'll see our placeholder instead!"

**Pull request merged**
