### PR TITLE
Revert "Prevent pathological queries when doc is not specified (#784)"

### PR DESCRIPTION
**Pull request by thecadams**
This reverts commit 046fd4775ad49eacdd8e9f59ed483a064531297c.

This is an emergency fix to restore admin functionality.

### CODE REVIEW

**Comment by thecadams** [comment]
@0xdevalias PTAL

**Review by 0xdevalias — APPROVED** [review]
Approved (retroactively).

Musing: I think for 'emergency fixes' we need a workflow where we can easily get them through to prod, even if there isn't necessarily someone around who can approve it.

My desire is that everything at least has a PR for visibility/documenting it/etc, but I don't necessarily think that needs to be reviewed/approved.

Have some thoughts i'll let brew on this and we can figure a good pattern/solution moving forward.

**Comment by 0xdevalias** [comment]
image

This highlights another issue with the way our current workflows are configured, at least for this use case. It's wanting us to make a squash merge for this.. but I think for a revert that may not be something we actually want to do.. not sure, what do you think?

**Comment by thecadams** [comment]
> Musing: I think for 'emergency fixes' we need a workflow where we can easily get them through to prod, even if there isn't necessarily someone around who can approve it.
> 
> My desire is that everything at least has a PR for visibility/documenting it/etc, but I don't necessarily think that needs to be reviewed/approved.

Yep we need ability to break glass. Asked here: https://stackoverflow.com/questions/64998944/ability-to-break-glass-and-bypass-github-branch-protection-for-emergency-fixes

**Comment by 0xdevalias** [comment]
That StackOverflow is great! Opened a draft PR at https://github.com/sparkletown/.github/pull/1 where we can make this happen! 🎉

**Pull request merged**
