### PR TITLE
fix the admin sidebar footer and global footer

### PR DESCRIPTION
**Pull request by denisdimitrov**
- Increases the global footer z-index and the position of the admin sidebar footer.

Staging:

current

New:

new

Fixes: N/A (Saw the problem, fixed the problem)

### CODE REVIEW

**Comment by goran-peoski-work** [comment]
I have a bit more comprehensive update here 
- https://github.com/sparkletown/sparkle/pull/2615/files that 
doesn't warrant making any new `position: fixed` elements.

**Review by goran-peoski-work — CHANGES_REQUESTED** [review]
Please take a look at `constants.scss` in https://github.com/sparkletown/sparkle/pull/2615/files and if that approach of updating z-layer indices relative to each other is viable alternative to adding more fixed positioned elements.

**Comment by denisdimitrov** [comment]
@goran-peoski-work  Why are you against `position: fixed`? It looks like this is exactly what we are trying to do but instead we are using `position: absolute` and trying to adapt it to act and look like `position: fixed`. `position: absolute` is more likely to break, like in the current case. Now that we have scrollbar on the page this broke, but if used `fixed` in the first place it would have still worked as intended.

**Comment by goran-peoski-work** [comment]
`position: absolute` is also bad.  I was against adding it to other places because of a component that was about to be deleted https://github.com/sparkletown/sparkle/pull/2645

**Comment by goran-peoski-work** [comment]
Another relevant PR:
- https://github.com/sparkletown/sparkle/pull/2635

Yes, the scrollbars still have things to desire for, but at least now there is an easier path to removing `position`, preset `height` etc.

**Comment by denisdimitrov** [comment]
UI has changed and this PR is no longer valid.

**Pull request closed without merging**
