### PR TITLE
do not unset background image width

### PR DESCRIPTION
**Pull request by Demarchist1**
this seems to save the placement co-ordinates correctly

### CODE REVIEW

**Review by thecadams — COMMENTED** [review]
Looking to understand why this fixes it. Is it that the background width was being stretched, misleading people into thinking their venue was in a different spot than the coordinates they’d dragged it to? If so, is there a 4000 pixel wide container somewhere that we need to fix?

**Comment by thecadams** [comment]
And further I’m wondering if some git blame can be done to uncover why the unset was put there in the first place.

**Comment by Demarchist1** [comment]
I don't know - I just noticed that the icon's x and y co-ords appeared to be double on the actual paddock compared to the admin venue screen. I was digging around trying to see what you had done to convert the coordinates, and noticed the PlayaContainer width being unset from the admin component but not any other components

**Comment by thecadams** [comment]
OK no prob, thanks for this one I'll go merge it.

**Pull request merged**
