### PR TITLE
Accept image/png image types

### PR DESCRIPTION
**Pull request by margulies**
The image type 'image/x-png' did not appear to accept uploads of some .png image files. The addition of 'image/png' as an option appeared to fix that issue.

(New to contributing to this repo, so starting small...)

### CODE REVIEW

**Review by denisdimitrov — APPROVED** [review]
LGTM!

**Review by 0xdevalias — APPROVED** [review]
Looks good, thanks for the contribution!

[nit/future cleanup]
- We should extract our supported file types into a `const` so we only have to update a single place.
- according to [this StackOverflow](https://stackoverflow.com/questions/2086374/what-is-the-difference-between-image-png-and-image-x-png), `x-png` exists from before it was standardised. Are we ever going to see that anymore these days? If not, we can probably remove it in favour of just `png`

**Comment by 0xdevalias** [comment]
Hey @margulies, could I please get you to push another commit to your branch. It seems our CI wasn't configured to run for external contributors.

You should be able to make an empty commit like:

```
git commit --allow-empty -m 'trigger CI'
```

Thanks!

**Comment by margulies** [comment]
Hi @0xdevalias, thanks! Just updated the PR — let me know if any further changes should be made. 

I have several other changes I've been using locally, and it would be helpful to chat about whether some might be useful to contribute.

**Comment by 0xdevalias** [comment]
@thecadams see this PR re: me closing your dupe in #835 

The CI hasn't picked it up even after I fixed our CI settings + a new push was made.

When I googled it, this was pointed to as a way to 'force' CI to pick it up, even if it was from an external contributor:

- https://github.com/jklukas/git-push-fork-to-upstream-branch

**Comment by thecadams** [comment]
OK trying to work with CircleCI here. I'll update the branch and see if that kicks it off.

**Comment by 0xdevalias** [comment]
@thecadams I just used https://github.com/sparkletown/sparkle/pull/821#issuecomment-735557208 to trigger CI, which seems to have been picked up now. Have now also merged current staging into it to keep it up to date, then this should be good to merge.

I believe we shouldn't have this issue in future as the CI settings should be fixed up for it now. I think this PR just landed in the weird space between what we had + what we fixed it to (or so I hope.. :p)

**Comment by 0xdevalias** [comment]
Ok, that didn't seem to work either, so I just created a new PR from the branch it created in https://github.com/sparkletown/sparkle/pull/839 and that allowed me to merge.

Hopefully this was 'the hard one', and now that our CI config should be correctly configured for forks, it will 'just work' in future.

Thanks again for your contribution @margulies !

**Pull request closed without merging**
