### PR TITLE
[old branch] track open tabs and remove location only on last one

### PR DESCRIPTION
**Pull request by 0xdevalias**
@sparkletown/engineering I noticed this sitting in our old branches when I was cleaning them up. It might not be directly useful anymore, but it also sounds like it could be a good idea, so wanted to bring it up here for discussion. If we don't need it, we can close this PR + delete the branch.

@denisdimitrov this seems to be one of your old branches

@mike-lvov you've been working on counting related things most recently

### CODE REVIEW

**Comment by denisdimitrov** [comment]
After the new implementation of room counting and location tracking introduced by Mike. I don't think this is necessary.

**Comment by 0xdevalias** [comment]
> After the new implementation of room counting and location tracking introduced by Mike. I don't think this is necessary.

@denisdimitrov Sounds good.

@mike-lvov Can you please confirm? If so, we can close this + delete the branch.

**Comment by 0xdevalias** [comment]
> I don't think this particular PR is useful, but the problem that is addressed here exists even now. One of the ways to overcome it would be to enable only one instance of the app running at any point in time.

@mike-lvov That would be one way to resolve it. This would be another.

You said it still exists, is there an existing backlog issue tracking this by chance? And if so, are you able to link it here?

**Comment by mike-lvov** [comment]
Unrelevant PR

**Pull request closed without merging**
