### PR TITLE
[env/burn-staging] Use separate inputs for day, month, year instead of calendar input

### PR DESCRIPTION
**Pull request by malaikaaiyar**
~not sure if this is the desired solution or not, but it's here~

A best effort solution for buggy calendar Date of Birth check.

**Before**:

sparkle-dob-02

**After**:

sparkle-dob-01

### CODE REVIEW

**Comment by malaikaaiyar** [comment]
we decided

**Review by malaikaaiyar — COMMENTED** [review]
The code itself looks good to me, but logic-wise you can put in the 31st for months that don't have the 31st in them (and 29-31 for february)

**Comment by goran-peoski-work** [comment]
> The code itself looks good to me, but logic-wise you can put in the 31st for months that don't have the 31st in them (and 29-31 for february)

Correct. I tried to get the code to actually check if it is invalid, it just ends up setting 31st of February as 3rd of March or something :shrug:

**Comment by malaikaaiyar** [comment]
Sounds good. I would approve this, but I can't because I'm the pull request owner

**Comment by sofisparkle** [comment]
This is an 18+ event, please confirm your date of birth to continue.

**Review by mike-lvov — APPROVED** [review]
If tested, lgtm

**Pull request merged**
